# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5a2d934641cb1a96313a1e94ec7502301805825960ce0251deac0bfe61cc37d8f99dd85f29b72df20834d5b33d644ab9c5f8dbea1ade491df005592bbc5a8bc

test:
  secret_key_base: d8cb6288362304476ec6b13564145471cd4e721c5b30e941018af24412ad7ed7802a220a914eebef86203a236706fb581938e22beea73b70afc803bdc00ed25b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
